### ISSUE TITLE
[KeyboardShortcuts] controller boxes are all visible  

### ISSUE THREAD

**Issue by h3oCharles** [ScientificGuy/BuckshotRouletteMods#3]
the boxes that would appear when using the controller are all visible at once, even if I'm not using it to traverse through the menus

![image](https://github.com/MSLaFaver/BuckshotRouletteMods/assets/8020330/8f3dfaaf-4a69-4436-a81d-7993631b7769)

the mods folder (ignore the "#" folder, it's all disabled mods)
![image](https://github.com/MSLaFaver/BuckshotRouletteMods/assets/8020330/bb16b3dd-93f0-4b9c-a6d8-0449bb2e7113)

V1.2.2-3 (Steam + BRML V2.0.3)

**Comment by MSLaFaver** [comment]
KeyboardShortcuts is not compatible with BR 1.2+. There are not currently plans to update.

**Comment by h3oCharles** [comment]
please label this mod as abandoned then

**Comment by MSLaFaver** [comment]
No. The mod still works fine with BR v1.1 as stated in the readme.
